### PR TITLE
Add support for TikTok

### LINKED ISSUE #120: Add tiktok
Add tiktok and only allow watching videos from links or by search

### PR DESCRIPTION
**Pull request by stevepdp**
Hi.

This PR adds support for TikTok and closes #120. Tested against Firefox and Chromium.

Please let me know if there's anything I should improve.

Thanks!

### CODE REVIEW

**Comment by sic-guno** [comment]
For the love of God, America and my spare time please pull this in

**Comment by Sun-Mountain** [comment]
Please!

**Comment by tobiasdalhof** [comment]
> For the love of God, America and my spare time please pull this in

@sic-guno Try https://github.com/tobiasdalhof/sanersocialmedia if you need TikTok support:

image

@stevepdp I'd consider to mute and pause all audio and container elements, like https://github.com/tobiasdalhof/sanersocialmedia/blob/main/packages/core/src/sites/tiktok.ts

**Comment by reciosonny** [comment]
I didn't see this update when I used the extension. Is this feature still alive?

**Pull request closed without merging**
