### PR TITLE
Added support for importing from CSV

### PR DESCRIPTION
**Pull request by iAmShakil**
options-screenshot
Allows uploading from a CSV file.

### CODE REVIEW

**Comment by iAmShakil** [comment]
@jordwest any plan on adding this?

**Comment by jordwest** [comment]
Hi @iAmShakil, this is a really nice addition, thanks, but could we remove the screenshot of the CSV? It's a little confusing for non-techies as it looks like a UI in itself, I'm imagining the bug reports from people trying to click and type in it :)

**Review by jordwest — CHANGES_REQUESTED** [review]
Hi @iAmShakil, this is a really nice addition, thanks, but could we remove the screenshot of the CSV? It's a little confusing for non-techies as it looks like a UI in itself, I'm imagining the bug reports from people trying to click and type in it :)

**Comment by iAmShakil** [comment]
@jordwest updated the PR. Please check.

**Comment by jordwest** [comment]
Sorry for the delay @iAmShakil, thanks for the change! Will merge it and it'll go out next time I do a release.

**Pull request merged**
