### PR TITLE
Instagram support

### PR DESCRIPTION
**Pull request by ryanmonro**
I've added support for hiding the Instagram feed, friend suggestions and stories. Everything that's not the navigation bar, really. Thanks for the extension @jordwest, this has really changed how I waste time on social media: there's nothing to do, so I log out and do something else! Love it.

### CODE REVIEW

**Review by MihaiVoinea — APPROVED** [review]
Hi @jordwest!

Would you consider taking a look at this PR when you get a chance and if possible getting this merged? I think Instagram would be a great addition to this extension! :D

**Comment by jordwest** [comment]
Hey @ryanmonro, thanks for the contribution and apologies for taking so long to get to it!

Going to merge this now, test it and push it out in the next release.

A lot of people are going to be very glad to see this :)

**Comment by ryanmonro** [comment]
Thanks @jordwest – glad to help out! I've been using this for months, Instagram isn't the time waster it used to be.

**Comment by FelipeGlauber** [comment]
Instagram lost support

**Pull request merged**
