### PR TITLE
Added Reddit Feed Eradicator (Home || All || Popular)

### PR DESCRIPTION
**Pull request by kessido**
Added Reddit support.

known issue: didn't manage to get the code to recognize Reddit dark-theme.

Ido

### CODE REVIEW

**Comment by jordwest** [comment]
This is a highly requested site, thank you!

I suspect a lot of people (including myself) are still using https://old.reddit.com, so it'd be good if we can cover that too. It looks like it's much simpler - the feed is just an element with a fixed id `#siteTable` and the paths seem to match up with new reddit

**Comment by jordwest** [comment]
Also I think I found a way to fix the dark mode problem.

Currently NFE looks at the background color of the `body` element to tell if its 'dark' or not, while reddit seems to leave the body unchanged and just style the background of individual elements.

When we inject NFE, we could update the `body` element like:

```
document.body.style.background = 'var(--newRedditTheme-body)';
```

It's a bit of a hack, but most of NFE is based on hacks so 🤷

**Comment by kessido** [comment]
Sure, few min.

**Comment by kessido** [comment]
done on both (Y)

**Pull request merged**
