### PR TITLE
Remove Twitter public feed if user is logged out

### PR DESCRIPTION
**Pull request by weeksling**
Related issue I created: https://github.com/jordwest/news-feed-eradicator/issues/262

This adds an `isLoggedOut` check to the twitter eradicate method, and then removes the public feed if the user is logged out.

### CODE REVIEW

**Review by nzawirski — APPROVED** [review]
Looks good, works for me :+1:

**Comment by nzawirski** [comment]
I don't. I think only @jordwest can merge changes

**Comment by jordwest** [comment]
Thank you @weeksling!

**Comment by jordwest** [comment]
Hmm for some reason it's not working for me, the selectors are working as expected but the feed remains while logged out. I'll publish this anyway in case it fixes it for others.

**Pull request merged**
